### PR TITLE
Improve badges and workflow

### PR DESCRIPTION
**Pull request by Akashic101**
This PR improves badges by giving them a background- and border-color bashed on their hash-value. This makes different badges easier to identify. I also added a check to see if a tag already exists. Right now it only prints to the console, I am sure that there is a better way to show this but I leave this to @BaldissaraMatheus .I also modified the starting-scripts to use `cross-env` to allow easier development on Windows as the current `npm run start` on both backend and frontend does not work there.

[NVM](https://github.com/nvm-sh/nvm) has been added as well to make sure every developer uses the name version of Node.

### CODE REVIEW

**Comment by BaldissaraMatheus** [comment]
Thank you so much for the contribution! I think those changes are really good, but may need some tweaks:
- cross-env package & script changes: I think it's great and can be merged as is;
- Verification when badge already exists: Pretty good too. Once this PR is merged I can move this validation to the input, like when you're trying to create a card with a name that has already been used;
- Different hex colors for the badges: I think this one should be tweaked. Right now you can already change badge colors, when you click on a badge in the expanded card it shows an option to change its color. Then you can pick one of 7 different colors, that are assigned as css custom colors and each color is defined in the css theme file. Then the badge color is persisted in a file named tags.json located in the /config folder. I think those segments can show it clearly:

expanded-card.jsx
image
adwaita.css
image
tags.json
image

So this change would prevent the user to choose an arbitrary color, which may be undesirable for some people. I think instead of generating a hex color we could change it to pick one of those 7 css custom properties. What do you think?

Also, when I was testing this PR I noticed this color changing feature I just mentioned doesn't seem to be working anymore, probably because the <dialog> element has priority over the z-index and the menu is being displayed behind it. Fortunately this bug is not present in the latest released version, so you can check this feature by cloning the last docker file or just checkouting to 1 or 2 previous commits.

**Comment by Akashic101** [comment]
Thanks for the reply. To be completely honest I didn't know that you can already assign a color to a badge, shows what I know :D In that case it makes sense to remove my feature, I'll revert the commit tomorrow. Also please let me know if you are happy with the version I chose for Node in the .nvmrc file, I just chose whatever I had currently installed on my PC

**Comment by BaldissaraMatheus** [comment]
I think you can keep this change, just change it to use one of the available colors. I think it would be good to have a random initial color instead of the default primary one. Also no need to rush on that, I can also work from this PR when I available.

About the version on .nvmrc, this version is fine but I think it should be consistent with the docker file, which uses node-18-alpine. So I think the docker image should be changed to node-20-alpine

**Comment by BaldissaraMatheus** [comment]
Changes merge on #110.

**Pull request closed without merging**
